apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-with-sc-based-pvc
spec:
  containers:
  - name: pod-volume-with-sc-based-pvc
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-pvc-with-sc-demo