# Shopping Cart Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
  labels:
    app: shopping-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: nginx:latest
        volumeMounts:
        - name: shopping-cart-html-volume
          mountPath: /usr/share/nginx/html/cart
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 150m
            memory: 192Mi
          limits:
            cpu: 300m
            memory: 384Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: shopping-cart-config
        - secretRef:
            name: shopping-cart-secret
      volumes:
      - name: shopping-cart-html-volume
        configMap:
          name: shopping-cart-html-config