apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-managed-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resource-demo
  template:
    metadata:
      labels:
        app: resource-demo
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      initContainers:      # Example with init container resources
      - name: init-data
        image: busybox
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        command: ['sh', '-c', 'echo "Initializing..." && sleep 5']