apiVersion: v1
kind: Pod
metadata:
  name: single-pod-resources
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"      # 250 millicores = 0.25 CPU
      limits:
        memory: "256Mi"
        cpu: "500m"      # 500 millicores = 0.5 CPU
  - name: sidecar
    image: fluentd
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"