apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
  - name: demo
    image: registry.k8s.io/pause:2.0
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cache
          topologyKey: topology.kubernetes.io/zone  # Same zone