apiVersion: v1
kind: Pod
metadata:
  name: special-app
  labels:
    app: special-app
spec:
  containers:
  - name: special-app
    image: nginx
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "special-user"
    effect: "NoSchedule"
  nodeSelector:
    hardware: gpu-new