apiVersion: v1
kind: Pod
metadata:
  name: pod-node-required-affinity 
spec:
  containers:
  - name: demo
    image: registry.k8s.io/pause:2.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - ap-southeast-1a