# Product Catalog Service
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-cip-service
spec:
  selector:
    app: product-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP