# A pod using all three interfaces
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: nginx
    image: nginx        # Uses CRI
    volumeMounts:      # Uses CSI
    - mountPath: /data
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-storage
# Pod automatically gets IP Address through CNI