apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-cm-demo
  labels:
    app: web-app
  namespace: default
spec:
  containers:
  - name: web-app
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: cm-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: cm-volume # Volumes for injecting configuration data using configmaps
    configMap:
      name: html-volume-config