apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-emptydir-demo
  labels:
    app: web-app
  namespace: default
spec:
  containers:
  - name: log-sidecar
    image: busybox
    command: ['sh', '-c', 'tail -n+1 -f /var/log/nginx/access.log']
    volumeMounts:
    - name: empty-dir-volume
      mountPath: /var/log/nginx
  - name: web-app
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: empty-dir-volume
      mountPath: /var/log/nginx
  volumes:
  - name: empty-dir-volume # Volumes shared between containers using emptyDir
    emptyDir: {}