apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-with-pvc-demo
spec:
  containers:
  - name: pod-volume-with-pvc-demo
    image: ubuntu:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - ap-southeast-1a
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-pvc-demo