# Order Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
        <h1>Hello, World, I am serving from Order Service!</h1>
    </body>
    </html>