# Order Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: nginx:latest
        volumeMounts:
        - name: order-service-html-volume
          mountPath: /usr/share/nginx/html/orders
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: order-service-config
        - secretRef:
            name: order-service-secret
        env:
        - name: SHOPPING_CART_SERVICE_HOST
          value: "http://shopping-cart-service.deafult.svc.cluster.local"
        - name: SHOPPING_CART_SERVICE_PORT
          value: "80"
      volumes:
      - name: order-service-html-volume
        configMap:
          name: order-service-html-config