# Order Service Secret
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
stringData:
  DB_PASSWORD: "very-secret-password"
  PAYMENT_API_KEY: "payment-gateway-secret-key"