apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  type: ClusterIP
  selector:
    app: product-catalog
  ports:
    - protocol: TCP
      # The port that the Service will expose within the cluster.
      # Other pods will connect to this service on this port.
      port: 80
      # The port on the container that the traffic will be forwarded to.
      # This must match the 'containerPort' in your Deployment.
      targetPort: 80